### PR TITLE
Check to see if the interator key is valid instead of null

### LINKED ISSUE #39: IteratorObservable should check Iterator::valid() for completion
https://github.com/ReactiveX/RxPHP/blob/a0ef3c25f7593832cc6b2970ba48a7f15a006ab1/lib/Rx/Observable/IteratorObservable.php#L32

This check does not work in all cases. With SplObjectStorage the key is just an integer that keeps incrementing.

### PR DESCRIPTION
**Pull request by davidwdan**
fixes #39

### CODE REVIEW

**Comment by davidwdan** [comment]
I'm not sure what to do about hhvm.  Travis uses v3.6, which is from aug 2015.  All of the tests pass with v3.11+.

**Comment by davidwdan** [comment]
I'm just going to skip the tests that aren't passing with HHVM less than v3.11.0

File: test/Rx/Functional/Observable/IteratorObservableTest.php [hunk 1]
```diff
@@ -104,6 +104,44 @@ public function generator_dispose()
...
 
+    /**
+     * @test
+     *
+     * @link https://github.com/ReactiveX/RxPHP/issues/39
+     */
+    public function splObjectStorage_many()
+    {
+
+        if (defined('HHVM_VERSION') && version_compare(HHVM_VERSION, '3.11.0', 'lt')) {
```
Comment (mbonneau) [inline test/Rx/Functional/Observable/IteratorObservableTest.php:115]: Does this mean that we only support HHVM at this version or higher? Is there a way to fix the functionality so that it does work in lower versions?

Comment (davidwdan) [reply test/Rx/Functional/Observable/IteratorObservableTest.php:115]: @mbonneau at this point, I don't think it makes any sense to support older versions of hhvm
